"""Locate the exact page of every quoted phrase that the notes file
research/notes/pq/turing-integration-constraints.md cites from a PDF or text
standard, and print a short snippet around it.

Topic: turing-integration-constraints (prefix tic_). Reproduces nothing
numerical by itself: it is the evidence trail for ledger rows marked
VERIFIED from NIST FIPS 203, SP 800-227, SP 800-185 and the X-Wing draft.
Each check prints FOUND with the 1-based PDF page, or MISSING. The script is
deterministic and exits 1 if any phrase is missing.

Usage (from the repository root):
    timeout 300 python research/scripts/pq/tic_source_checks.py
"""
import pathlib
import re
import sys

import pymupdf as fitz

sys.stdout.reconfigure(encoding="utf-8")
ROOT = pathlib.Path(__file__).resolve().parents[3]
PAPERS = ROOT / "research" / "papers"

# (file, phrase). Whitespace in the page text is collapsed before matching,
# and the phrase is matched case-sensitively as plain text.
CHECKS = [
    # FIPS 203: randomness, input checking, sizes, hash functions.
    ("nist-fips-203-ml-kem.pdf", "These random bytes shall be generated using an approved RBG"),
    ("nist-fips-203-ml-kem.pdf", "at least 192 bits for ML-KEM-768"),
    ("nist-fips-203-ml-kem.pdf", "require input checking"),
    ("nist-fips-203-ml-kem.pdf", "shall be generated by the cryptographic module"),
    ("nist-fips-203-ml-kem.pdf", "Table 3. Sizes (in bytes) of keys and ciphertexts of ML-KEM"),
    ("nist-fips-203-ml-kem.pdf", "Table 2. Approved parameter sets for ML-KEM"),
    ("nist-fips-203-ml-kem.pdf", "4.1 Cryptographic Functions"),
    ("nist-fips-203-ml-kem.pdf", "SHAKE256"),
    ("nist-fips-203-ml-kem.pdf", "Encapsulation key check"),
    ("nist-fips-203-ml-kem.pdf", "Decapsulation input check"),
    ("nist-fips-203-ml-kem.pdf", "(Hash check)"),
    ("nist-fips-203-ml-kem.pdf", "3.3 Requirements for ML-KEM Implementations"),
    ("nist-fips-203-ml-kem.pdf", "Destruction of intermediate values"),
    ("nist-fips-203-ml-kem.pdf", "can be stored for later expansion using ML-KEM.KeyGen_internal"),
    ("nist-fips-203-ml-kem.pdf", "ML-KEM.KeyGen_internal"),
    ("nist-fips-203-ml-kem.pdf", "ML-KEM-768 (security category 3)"),
    ("nist-fips-203-ml-kem.pdf", "ML-KEM-1024 (security category 5)"),
    ("nist-fips-203-ml-kem.pdf", "The security categories 1-5 are defined in SP 800-57, Part 1"),
    ("nist-fips-203-ml-kem.pdf", "Key pair check"),
    ("nist-fips-203-ml-kem.pdf", "Pair-wise consistency"),
    ("nist-fips-203-ml-kem.pdf", "Ciphertext checking shall be performed with every execution of ML-KEM.Decaps"),
    ("nist-fips-203-ml-kem.pdf", "Implementations of ML-KEM shall not use floating-point arithmetic"),
    ("nist-fips-203-ml-kem.pdf", "Controlled access to internal functions"),
    ("nist-fips-203-ml-kem.pdf", "SamplePolyCBD"),
    # SP 800-227: KEM usage recommendations.
    ("nist-sp800-227-kem-recommendations.pdf", "key combiner"),
    # FrodoKEM preliminary standardization proposal (2025-09-29).
    ("2025-alkim-et-al-frodokem-standard-proposal-20250929.pdf", "Table A.1"),
    ("2025-alkim-et-al-frodokem-standard-proposal-20250929.pdf", "FrodoKEM-976 31,296 15,632 15,792 24"),
    ("2025-alkim-et-al-frodokem-standard-proposal-20250929.pdf", "security of AES192"),
    ("2025-alkim-et-al-frodokem-standard-proposal-20250929.pdf", "Table A.4"),
    ("2025-alkim-et-al-frodokem-standard-proposal-20250929.pdf", "SHAKE128 (parameter sets FrodoKEM-640-SHAKE"),
    # KyberSlash (division timing).
    ("2025-bernstein-et-al-kyberslash.pdf", "asking gcc to optimize for code size (-Os) generally disables the conversion of divisions into multiplications"),
    ("2025-bernstein-et-al-kyberslash.pdf", "gcc 14.1.0 from May 2024 produces division instructions even when it is optimizing for speed"),
    ("2025-bernstein-et-al-kyberslash.pdf", "but also for secret divisions"),
    # SP 800-185: cSHAKE definition.
    ("nist-sp800-185-sha3-derived-functions.pdf", "cSHAKE256(X, L, N, S)"),
    ("nist-sp800-185-sha3-derived-functions.pdf", "When N and S are both empty strings"),
]


# Phrases the notes say a document does NOT contain (whole-document search).
ABSENT = [
    ("nist-sp800-90c-rbg-constructions.pdf", "SHAKE"),
    ("nist-sp800-90c-rbg-constructions.pdf", "XOF"),
    ("nist-sp800-90c-rbg-constructions.pdf", "KMAC"),
]
CHECKS += [
    ("nist-sp800-90c-rbg-constructions.pdf", "https://doi.org/10.6028/NIST.SP.800-90C"),
    ("nist-sp800-90c-rbg-constructions.pdf", "For CTR_DRBG with a derivation function, Hash_DRBG, or HMAC_DRBG"),
]


def page_texts(path):
    doc = fitz.open(path)
    return [re.sub(r"\s+", " ", doc[i].get_text()) for i in range(doc.page_count)]


def main():
    cache = {}
    missing = 0
    for name, phrase in CHECKS:
        path = PAPERS / name
        if not path.exists():
            print(f"MISSING FILE {name}")
            missing += 1
            continue
        if name not in cache:
            cache[name] = page_texts(path)
        pages = [i + 1 for i, t in enumerate(cache[name]) if phrase in t]
        if not pages:
            print(f"MISSING  {name}: {phrase!r}")
            missing += 1
            continue
        first = pages[0]
        text = cache[name][first - 1]
        at = text.index(phrase)
        snippet = text[max(0, at - 80): at + len(phrase) + 160]
        print(f"FOUND    {name} PDF p.{','.join(map(str, pages[:6]))}: {phrase!r}")
        print(f"         ...{snippet}...")
    print(f"{len(CHECKS) - missing} of {len(CHECKS)} phrases found")
    present = 0
    for name, phrase in ABSENT:
        if name not in cache:
            cache[name] = page_texts(PAPERS / name)
        hits = sum(t.count(phrase) for t in cache[name])
        present += hits > 0
        print(f"{'ABSENT ' if hits == 0 else 'PRESENT'}  {name}: {phrase!r} ({hits} occurrences)")
    return 1 if missing or present else 0


if __name__ == "__main__":
    sys.exit(main())
