//! Known-answer self-test, in the spirit of the cryptographic algorithm
//! self-tests FIPS 140-3 requires before a module uses an algorithm. A
//! miscompiled or corrupted build (a compiler that rewrites the bit-sliced
//! code, a flipped bit in the binary, a broken sha3 dependency) fails here,
//! loudly, instead of producing ciphertexts nobody can decrypt or, worse,
//! weak ones. Call it once at start-up, before any real key is used.
//!
//! The vectors come from `vectors/turing-v2.txt` (generated by the
//! independent reference implementation in Bombe, whose tests check these
//! constants against it) and NIST's published cSHAKE256 example values.

use crate::{xof, Turing};
use sha3::digest::XofReader;

/// Which part of the self-test failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SelfTestError {
    /// cSHAKE256 does not reproduce NIST's example value.
    Xof,
    /// A known-answer vector encrypted to the wrong ciphertext.
    Encrypt,
    /// A known-answer ciphertext did not decrypt back to its plaintext.
    Decrypt,
}

/// NIST SP 800-185 cSHAKE256 sample #3: S = "Email Signature", X = 00010203.
pub const XOF_SAMPLE: [u8; 32] = [
    0xd0, 0x08, 0x82, 0x8e, 0x2b, 0x80, 0xac, 0x9d, 0x22, 0x18, 0xff, 0xee, 0x1d, 0x07, 0x0c, 0x48, 0xb8, 0xe4, 0xc8, 0x7b,
    0xff, 0x32, 0xc9, 0x69, 0x9d, 0x5b, 0x68, 0x96, 0xee, 0xe0, 0xed, 0xd1,
];

/// (key, plaintext, ciphertext): vectors 0 and 2 of `vectors/turing-v2.txt`.
pub const VECTORS: [([u8; 32], [u8; 16], [u8; 16]); 2] = [
    (
        [0; 32],
        [0; 16],
        [0x09, 0xae, 0x63, 0xc1, 0xfc, 0x6c, 0xe9, 0xd0, 0xe7, 0xb8, 0x1a, 0x53, 0xf0, 0x7f, 0x85, 0x7f],
    ),
    (
        [
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13,
            0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
        ],
        [0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff],
        [0x13, 0xce, 0x4b, 0xdc, 0xb5, 0x48, 0x22, 0x8c, 0xa2, 0x71, 0xf9, 0xdd, 0xcc, 0xa3, 0x07, 0xd8],
    ),
];

/// Runs every check; the first failure is returned.
pub fn self_test() -> Result<(), SelfTestError> {
    let mut out = [0u8; 32];
    xof::cshake256("Email Signature", &[0, 1, 2, 3]).read(&mut out);
    let mut secret = [0u8; 32];
    xof::cshake256_secret("Email Signature", &[0, 1, 2, 3], &mut secret);
    if out != XOF_SAMPLE || secret != XOF_SAMPLE {
        return Err(SelfTestError::Xof);
    }
    for (key, plaintext, ciphertext) in &VECTORS {
        let t = Turing::new(key);
        let mut block = *plaintext;
        t.encrypt_block(&mut block);
        if block != *ciphertext {
            return Err(SelfTestError::Encrypt);
        }
        t.decrypt_block(&mut block);
        if block != *plaintext {
            return Err(SelfTestError::Decrypt);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn self_test_passes() {
        assert_eq!(self_test(), Ok(()));
    }
}
