"""Builds vectors/ml-kem-fips203.txt, the ML-KEM known-answer tests that
crates/bombe/tests/mlkem.rs runs, from the official sources:

- NIST ACVP-Server sample vectors for FIPS 203 (final): ML-KEM-keyGen-FIPS203
  and ML-KEM-encapDecap-FIPS203 (key generation, encapsulation, decapsulation,
  encapsulation-key and decapsulation-key checks), plus the seed-format
  decapsulation groups of ML-KEM-encapDecap-FIPS203-tr1. Works of the US
  government: public domain.
- C2SP CCTV ML-KEM (CC0 1.0): the "strcmp" and "unluckysample" vectors. CCTV
  targets FIPS 203 ipd with the matrix-index fix, i.e. key generation from
  G(d) rather than the final G(d || k); the test runs them in that mode.

Outputs that are large and are not inputs to anything (ek and dk from key
generation, c from encapsulation) are stored as their SHA3-256; everything
the implementation reads is stored in full.

    python tools/ml_kem_vectors.py [SOURCE_DIR]    (default research/workfiles/pq/vectors)
"""
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "research" / "workfiles" / "pq" / "vectors"
OUT = ROOT / "vectors" / "ml-kem-fips203.txt"


def sha3(hexstr):
    return hashlib.sha3_256(bytes.fromhex(hexstr)).hexdigest()


def sha256_file(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def acvp(name):
    d = SRC / "acvp" / name
    prompt, expected = json.loads((d / "prompt.json").read_text()), json.loads((d / "expectedResults.json").read_text())
    results = {(g["tgId"], t["tcId"]): t for g in expected["testGroups"] for t in g["tests"]}
    sources.extend([d / "prompt.json", d / "expectedResults.json"])
    return prompt["testGroups"], results


def case(lines, fields):
    # ACVP writes hex in upper case, CCTV and hashlib in lower case: normalise.
    for k, v in fields:
        lines.append(f"{k} = {str(v).lower()}")
    lines.append("")


sources = []
lines = []

groups, res = acvp("ML-KEM-keyGen-FIPS203")
for g in groups:
    lines.append(f"[keyGen {g['parameterSet']}]")
    for t in g["tests"]:
        r = res[(g["tgId"], t["tcId"])]
        case(lines, [("tcId", t["tcId"]), ("d", t["d"]), ("z", t["z"]), ("ek_sha3", sha3(r["ek"])), ("dk_sha3", sha3(r["dk"]))])

groups, res = acvp("ML-KEM-encapDecap-FIPS203")
for g in groups:
    ps, fn = g["parameterSet"], g["function"]
    for t in g["tests"]:
        r = res[(g["tgId"], t["tcId"])]
        if fn == "encapsulation":
            lines.append(f"[encaps {ps}]")
            case(lines, [("tcId", t["tcId"]), ("ek", t["ek"]), ("m", t["m"]), ("c_sha3", sha3(r["c"])), ("k", r["k"])])
        elif fn == "decapsulation":
            lines.append(f"[decaps {ps}]")
            case(lines, [("tcId", t["tcId"]), ("dk", t["dk"]), ("c", t["c"]), ("k", r["k"])])
        elif fn == "encapsulationKeyCheck":
            lines.append(f"[ekCheck {ps}]")
            case(lines, [("tcId", t["tcId"]), ("ek", t["ek"]), ("valid", int(r["testPassed"]))])
        elif fn == "decapsulationKeyCheck":
            lines.append(f"[dkCheck {ps}]")
            case(lines, [("tcId", t["tcId"]), ("dk", t["dk"]), ("valid", int(r["testPassed"]))])
        else:
            raise SystemExit(f"unknown function {fn}")

groups, res = acvp("ML-KEM-encapDecap-FIPS203-tr1")
for g in groups:
    if g["function"] == "decapsulation" and g.get("keyFormat") == "seed":
        for t in g["tests"]:
            r = res[(g["tgId"], t["tcId"])]
            lines.append(f"[decapsSeed {g['parameterSet']}]")
            case(lines, [("tcId", t["tcId"]), ("d", t["d"]), ("z", t["z"]), ("c", t["c"]), ("k", r["k"])])


def cctv_file(p):
    sources.append(p)
    out = {}
    for line in p.read_text().splitlines():
        if " = " in line:
            k, v = line.split(" = ", 1)
            out[k.strip()] = v.strip()
    return out


for ps in ["ML-KEM-512", "ML-KEM-768", "ML-KEM-1024"]:
    s = cctv_file(SRC / "cctv" / "strcmp" / f"{ps}.txt")
    lines.append(f"[cctvStrcmp {ps}]")
    case(lines, [("dk", s["dk"]), ("c", s["c"]), ("k", s["K"])])
    u = cctv_file(SRC / "cctv" / "unluckysample" / f"{ps}.txt")
    lines.append(f"[cctvUnluckyIpd {ps}]")
    case(lines, [("d", u["d"]), ("z", u["z"]), ("ek_sha3", sha3(u["ek"])), ("dk_sha3", sha3(u["dk"])), ("m", u["m"]), ("c_sha3", sha3(u["c"])), ("k", u["K"])])

header = [
    "# ML-KEM (FIPS 203) known-answer tests, generated by tools/ml_kem_vectors.py.",
    "# NIST ACVP-Server sample vectors (public domain) and C2SP CCTV (CC0 1.0).",
    "# [cctv* ...] sections follow FIPS 203 ipd key generation, G(d); all others the final G(d || k).",
    "# *_sha3 fields are SHA3-256 of the value. Sources (SHA-256):",
] + [f"#   {sha256_file(p)}  {p.relative_to(SRC).as_posix()}" for p in sources]
OUT.write_text("\n".join(header + [""] + lines), encoding="utf-8", newline="\n")
counts = {}
for line in lines:
    if line.startswith("["):
        kind = line[1:].split()[0]
        counts[kind] = counts.get(kind, 0) + 1
print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB): {counts}")
