//! Derives the Turing S-box from a public label.
//!
//! Candidate n is S(x) = A_out(inv(A_in(x))), where the affine maps are read
//! from SHAKE256(LABEL || n as u32 big-endian): 8 bytes of matrix rows
//! (redrawn while singular), then 1 constant byte, first for A_in then A_out.
//! The first candidate that passes every Bombe check is Turing's S-box.
//! Taking the first, not the best-looking, is what keeps the choice honest:
//! anyone can rerun this and nobody could have steered the result.

use crate::report::Report;
use crate::sbox::{Sbox, N};
use sha3::digest::{ExtendableOutput, Update, XofReader};
use sha3::Shake256;
use std::fmt::Write;
use turing::gf::{self, Affine};

pub const LABEL: &str = "Turing v1 S-box";

/// A SHAKE256 output stream for `label || counter` (big-endian).
pub fn shake(label: &str, counter: u32) -> impl XofReader {
    let mut h = Shake256::default();
    h.update(label.as_bytes());
    h.update(&counter.to_be_bytes());
    h.finalize_xof()
}

fn draw_affine(reader: &mut impl XofReader) -> Affine {
    loop {
        let mut rows = [0u8; 8];
        reader.read(&mut rows);
        if gf::invert_matrix(rows).is_some() {
            let mut constant = [0u8; 1];
            reader.read(&mut constant);
            return Affine::new(rows, constant[0]);
        }
    }
}

pub struct Candidate {
    pub counter: u32,
    pub a_in: Affine,
    pub a_out: Affine,
    pub sbox: Sbox,
}

pub fn candidate(counter: u32) -> Candidate {
    let mut reader = shake(LABEL, counter);
    let a_in = draw_affine(&mut reader);
    let a_out = draw_affine(&mut reader);
    let mut table = [0u8; N];
    for (x, out) in table.iter_mut().enumerate() {
        *out = a_out.apply(gf::inv(a_in.apply(x as u8)));
    }
    Candidate { counter, a_in, a_out, sbox: Sbox::new(table) }
}

pub struct Search {
    pub chosen: Candidate,
    pub report: Report,
    /// Every earlier candidate and the checks it failed.
    pub rejected: Vec<(u32, Vec<&'static str>)>,
}

pub fn search() -> Search {
    let mut rejected = Vec::new();
    for counter in 0..=u32::MAX {
        let c = candidate(counter);
        let report = Report::new("Turing S-box", &c.sbox);
        let mut failed: Vec<&'static str> = report.checks.iter().filter(|k| !k.pass).map(|k| k.name).collect();
        if c.sbox == Sbox::aes() {
            failed.push("identical to AES");
        }
        if failed.is_empty() {
            return Search { chosen: c, report, rejected };
        }
        rejected.push((counter, failed));
    }
    unreachable!("no acceptable candidate in 2^32 draws")
}

fn hex_list(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", ")
}

/// The generated `crates/turing/src/sbox_constants.rs`.
pub fn render_rust(s: &Search) -> String {
    let c = &s.chosen;
    let in_inv = gf::invert_affine(&c.a_in).expect("drawn matrices are invertible");
    let out_inv = gf::invert_affine(&c.a_out).expect("drawn matrices are invertible");
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "// @generated by `bombe gen-sbox --rust crates/turing/src/sbox_constants.rs`.");
    let _ = writeln!(w, "// Do not edit: a Bombe test regenerates this file and requires an exact match.");
    let _ = writeln!(w, "//");
    let _ = writeln!(w, "// Source: SHAKE256(\"{LABEL}\" || counter as u32 big-endian).");
    let _ = writeln!(w, "// {} is the first counter Bombe accepted; {} earlier ones were rejected.", c.counter, s.rejected.len());
    let _ = writeln!(w);
    let _ = writeln!(w, "/// The SHAKE256 counter this S-box was derived from.");
    let _ = writeln!(w, "pub const TABLE_COUNTER: u32 = {};", c.counter);
    for (name, a) in [("IN", &c.a_in), ("OUT", &c.a_out), ("IN_INV", &in_inv), ("OUT_INV", &out_inv)] {
        let _ = writeln!(w, "pub const {name}_ROWS: [u8; 8] = [{}];", hex_list(&a.rows));
        let _ = writeln!(w, "pub const {name}_CONST: u8 = 0x{:02x};", a.constant);
    }
    let _ = writeln!(w, "/// S(x) for x = 0..=255. For analysis and tests; the cipher computes S in");
    let _ = writeln!(w, "/// constant time instead of looking it up.");
    let _ = writeln!(w, "pub const TABLE: [u8; 256] = [");
    for row in c.sbox.table().chunks(16) {
        let _ = writeln!(w, "    {},", hex_list(row));
    }
    let _ = writeln!(w, "];");
    out
}
