//! Derives Turing's constants from public labels: the S-box (below) and the
//! Cauchy mixing matrices (further down).
//!
//! Candidate n is S(x) = A_out(inv(A_in(x))), where the affine maps are read
//! from cSHAKE256(X = n as u32 big-endian, S = LABEL): 8 bytes of matrix rows
//! (redrawn while singular), then 1 constant byte, first for A_in then A_out.
//! The first candidate that passes every Bombe check is Turing's S-box.
//! Taking the first, not the best-looking, is what keeps the choice honest:
//! anyone can rerun this and nobody could have steered the result.

use crate::gf256;
use crate::matrix::{self, Matrix, MdsReport};
use crate::report::Report;
use crate::sbox::{Sbox, N};
use sha3::digest::XofReader;
use std::fmt::Write;
use turing::gf::{self, Affine};

pub const LABEL: &str = "Turing v1 S-box";

/// The derivation stream for `counter` under `label`: cSHAKE256 with the
/// counter (big-endian) as input and the label as customization string.
pub fn stream(label: &str, counter: u32) -> impl XofReader {
    turing::xof::cshake256(label, &counter.to_be_bytes())
}

fn draw_affine(reader: &mut impl XofReader) -> Affine {
    loop {
        let mut rows = [0u8; 8];
        reader.read(&mut rows);
        if gf::invert_matrix(rows).is_some() {
            let mut constant = [0u8; 1];
            reader.read(&mut constant);
            return Affine::new(rows, constant[0]);
        }
    }
}

pub struct Candidate {
    pub counter: u32,
    pub a_in: Affine,
    pub a_out: Affine,
    pub sbox: Sbox,
}

pub fn candidate(counter: u32) -> Candidate {
    let mut reader = stream(LABEL, counter);
    let a_in = draw_affine(&mut reader);
    let a_out = draw_affine(&mut reader);
    let mut table = [0u8; N];
    for (x, out) in table.iter_mut().enumerate() {
        *out = a_out.apply(gf::inv(a_in.apply(x as u8)));
    }
    Candidate { counter, a_in, a_out, sbox: Sbox::new(table) }
}

pub struct Search {
    pub chosen: Candidate,
    pub report: Report,
    /// Every earlier candidate and the checks it failed.
    pub rejected: Vec<(u32, Vec<&'static str>)>,
}

pub fn search() -> Search {
    let mut rejected = Vec::new();
    for counter in 0..=u32::MAX {
        let c = candidate(counter);
        let report = Report::new("Turing S-box", &c.sbox);
        let mut failed: Vec<&'static str> = report.checks.iter().filter(|k| !k.pass).map(|k| k.name).collect();
        if c.sbox == Sbox::aes() {
            failed.push("identical to AES");
        }
        if failed.is_empty() {
            return Search { chosen: c, report, rejected };
        }
        rejected.push((counter, failed));
    }
    unreachable!("no acceptable candidate in 2^32 draws")
}

fn hex_list(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", ")
}

/// The generated `crates/turing/src/sbox_constants.rs`.
pub fn render_rust(s: &Search) -> String {
    let c = &s.chosen;
    let in_inv = gf::invert_affine(&c.a_in).expect("drawn matrices are invertible");
    let out_inv = gf::invert_affine(&c.a_out).expect("drawn matrices are invertible");
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(w, "// @generated by `bombe gen-sbox --rust crates/turing/src/sbox_constants.rs`.");
    let _ = writeln!(w, "// Do not edit: a Bombe test regenerates this file and requires an exact match.");
    let _ = writeln!(w, "//");
    let _ = writeln!(w, "// Source: cSHAKE256(X = counter as u32 big-endian, S = \"{LABEL}\").");
    let _ = writeln!(w, "// {} is the first counter Bombe accepted; {} earlier ones were rejected.", c.counter, s.rejected.len());
    let _ = writeln!(w);
    let _ = writeln!(w, "/// The cSHAKE256 counter this S-box was derived from.");
    let _ = writeln!(w, "pub const TABLE_COUNTER: u32 = {};", c.counter);
    for (name, a) in [("IN", &c.a_in), ("OUT", &c.a_out), ("IN_INV", &in_inv), ("OUT_INV", &out_inv)] {
        let _ = writeln!(w, "pub const {name}_ROWS: [u8; 8] = [{}];", hex_list(&a.rows));
        let _ = writeln!(w, "pub const {name}_CONST: u8 = 0x{:02x};", a.constant);
    }
    let _ = writeln!(w, "/// S(x) for x = 0..=255. For analysis and tests; the cipher computes S in");
    let _ = writeln!(w, "/// constant time instead of looking it up.");
    let _ = writeln!(w, "pub const TABLE: [u8; 256] = [");
    for row in c.sbox.table().chunks(16) {
        let _ = writeln!(w, "    {},", hex_list(row));
    }
    let _ = writeln!(w, "];");
    out
}

// ---------------------------------------------------------------------------
// Mixing matrices
// ---------------------------------------------------------------------------

pub const COLUMNS_LABEL: &str = "Turing v1 MixColumns";
pub const STATE_LABEL: &str = "Turing v1 MixState";

/// A Cauchy matrix M[i][j] = 1/(x_i + y_j) and its derivation.
pub struct CauchyMatrix {
    pub label: &'static str,
    pub counter: u32,
    pub xs: Vec<u8>,
    pub ys: Vec<u8>,
    pub m: Matrix,
    pub m_inv: Matrix,
    pub report: MdsReport,
}

/// Reads bytes from cSHAKE256(counter, S = label), skipping repeats, until it
/// has 2n distinct points: the first n are x, the rest y. Distinct points
/// make every x_i + y_j non-zero and the matrix MDS by the Cauchy theorem;
/// Bombe then checks MDS independently. The first counter that passes is used.
pub fn cauchy(label: &'static str, n: usize) -> CauchyMatrix {
    for counter in 0..=u32::MAX {
        let mut reader = stream(label, counter);
        let mut points: Vec<u8> = Vec::with_capacity(2 * n);
        while points.len() < 2 * n {
            let mut b = [0u8; 1];
            reader.read(&mut b);
            if !points.contains(&b[0]) {
                points.push(b[0]);
            }
        }
        let (xs, ys) = (points[..n].to_vec(), points[n..].to_vec());
        let m: Matrix = xs.iter().map(|&x| ys.iter().map(|&y| gf256::fast_inv(x ^ y)).collect()).collect();
        let Some(m_inv) = matrix::invert(&m) else { continue };
        let report = MdsReport::new(&m, &m_inv);
        if report.passed() {
            return CauchyMatrix { label, counter, xs, ys, m, m_inv, report };
        }
    }
    unreachable!("no MDS matrix in 2^32 draws")
}

pub struct Linear {
    pub columns: CauchyMatrix,
    pub state: CauchyMatrix,
}

pub fn linear() -> Linear {
    Linear { columns: cauchy(COLUMNS_LABEL, 4), state: cauchy(STATE_LABEL, 16) }
}

fn matrix_const(name: &str, m: &Matrix) -> String {
    let n = m.len();
    let mut out = format!("pub const {name}: [[u8; {n}]; {n}] = [\n");
    for row in m {
        out += &format!("    [{}],\n", hex_list(row));
    }
    out + "];\n"
}

/// The generated `crates/turing/src/linear_constants.rs`.
pub fn render_linear_rust(l: &Linear) -> String {
    let mut out = String::new();
    out += "// @generated by `bombe gen-linear --rust crates/turing/src/linear_constants.rs`.\n";
    out += "// Do not edit: a Bombe test regenerates this file and requires an exact match.\n";
    out += "//\n";
    out += "// Cauchy matrices M[i][j] = 1/(x_i + y_j) over GF(2^8). The 2n distinct points\n";
    out += "// are the first distinct bytes of cSHAKE256(X = counter as u32 big-endian, S = label).\n";
    for (name, c) in [("COLUMNS", &l.columns), ("STATE", &l.state)] {
        out += &format!("\n// {name}: label \"{}\", counter {}.\n", c.label, c.counter);
        out += &format!("pub const {name}_X: [u8; {}] = [{}];\n", c.xs.len(), hex_list(&c.xs));
        out += &format!("pub const {name}_Y: [u8; {}] = [{}];\n", c.ys.len(), hex_list(&c.ys));
    }
    out += "\n";
    out += &matrix_const("MIX_COLUMNS", &l.columns.m);
    out += &matrix_const("MIX_COLUMNS_INV", &l.columns.m_inv);
    out += &matrix_const("MIX_STATE", &l.state.m);
    out += &matrix_const("MIX_STATE_INV", &l.state.m_inv);
    out
}
